version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oiltracker
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports: ["6379:6379"]
  backend:
    build: ../backend
    env_file:
      - ../backend/.env.example
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/oiltracker
    depends_on: [db, redis]
    ports:
      - "8000:8000"
  frontend:
    build: ../frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on: [backend]
    ports:
      - "3000:3000"
